version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: school2
    environment:
      POSTGRES_USER: mei
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: school
    ports:
      - "55000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://mei:123@postgres1:5432/school
    depends_on:
      - postgres

volumes:
  postgres_data:
