version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: school
    environment:
      POSTGRES_USER: mei
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U mei -d school'"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://mei:123@postgres:5432/school
    depends_on:
      - postgres
    command: bash -c "npx prisma migrate dev --name init && npm start"

volumes:
  postgres_data:
